config/routes.rb
Rails.application.routes.draw do
  resources :tape_formats
  resources :formats
  resources :brands
  resources :conditions
  resources :physicals, path: 'tapes' do
    get 'digitize' => 'projects#digitize'
    post 'digitize' => 'projects#create_by_tape'
  end
  resources :digitals
  resources :projects
  resources :filmmakers
  resources :owners
  # resources :serials
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :projects
  has_many :physicals

  validates :owner_name, presence: true, uniqueness: true
  validates :contact_name, :contact_email, :contact_phone, presence: true

  before_destroy :ensure_not_referenced_by_any_physicals

  private

  def ensure_not_referenced_by_any_physicals
    if physicals.empty?
      return true
    else
      logger.error "Attempt to delete owner which has physicals."
      return false
    end
  end
end

# == Schema Information
#
# Table name: owners
#
#  id            :integer          not null, primary key
#  owner_name    :string
#  contact_name  :string
#  contact_email :string
#  contact_phone :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_vip_or_admin!, except: [:show, :index]
  before_action :authenticate_admin!, only: [:destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    respond_to do |format|
      if @owner.destroy
        format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to owners_url, alert: 'Cannot delete because some tapes use this owner.'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:owner_name, :contact_name, :contact_email, :contact_phone)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner_name %><br>
    <%= f.text_field :owner_name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Content Owners</h1>
<p>
  <%= link_to 'Enter a New Owner', new_owner_path, class: 'btn btn-default' %>
</p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Owner name</th>
      <th>Contact name</th>
      <th>Contact email</th>
      <th>Contact phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.owner_name %></td>
        <td><%= owner.contact_name %></td>
        <td><%= owner.contact_email %></td>
        <td><%= owner.contact_phone %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  var offset = $('.navbar').height();
  $('table').stickyTableHeaders({fixedOffset: offset});
</script>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p>
  <strong>Owner name:</strong>
  <%= @owner.owner_name %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @owner.contact_name %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @owner.contact_email %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @owner.contact_phone %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>