config/routes.rb
Rails.application.routes.draw do
  resources :tape_formats
  resources :formats
  resources :brands
  resources :conditions
  resources :physicals, path: 'tapes' do
    get 'digitize' => 'projects#digitize'
    post 'digitize' => 'projects#create_by_tape'
  end
  resources :digitals
  resources :projects
  resources :filmmakers
  resources :owners
  # resources :serials
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/project.rb
class Project < ActiveRecord::Base
  # belongs_to :serial
  belongs_to :owner
  # has_and_belongs_to_many :filmmakers
  has_many :physical_projects
  has_many :physicals, through: :physical_projects

  has_many :digitals
  accepts_nested_attributes_for :digitals, :reject_if => :all_blank, :allow_destroy => true

  validates :owner_id, :title, presence: true
  validates :title, uniqueness: true

  before_destroy :ensure_not_referenced_by_any_physicals

  private

  def ensure_not_referenced_by_any_physicals
    if physical_projects.empty?
      return true
    else
      logger.error "Attempt to delete project which has physicals through physical_projects."
      return false
    end
  end
end

# == Schema Information
#
# Table name: projects
#
#  id               :integer          not null, primary key
#  serial_id        :integer          default(1)
#  owner_id         :integer
#  title            :string
#  description      :text
#  production_notes :text
#  production_year  :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  date_production  :date
#  credits          :text
#
# Indexes
#
#  index_projects_on_owner_id   (owner_id)
#  index_projects_on_serial_id  (serial_id)
#

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_vip_or_admin!, except: [:show, :index]
  before_action :authenticate_admin!, only: [:destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @serials = Serial.all
    @owners = Owner.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @serials = Serial.all
    @owners = Owner.all
  end

  # GET /projects/1/edit
  def edit
    @serials = Serial.all
    @owners = Owner.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @serials = Serial.all
    @owners = Owner.all

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_by_tape
    @physical = Physical.find(params[:physical_id])

    if @physical.projects.create(project_params)
      redirect_to @physical, notice: 'Project successfully saved!'
    else
      # TODO: make sure it renders the digitize view with validation errors
      render :digitize
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to owners_url, alert: 'Cannot delete because other records reference this project.'}
      end
    end
  end

  def digitize
    @owners = Owner.all
    @physical = Physical.find(params[:physical_id])
    @project = @physical.projects.build
    # @project.digitals.build
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:serial_id, :owner_id, :title, :description, :production_notes, :date_production, :production_year, :credits)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :production_notes %><br>
    <%= f.text_area :production_notes, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :credits %><br>
    <%= f.text_area :credits, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :date_production %><br>
    <%= f.text_field :date_production, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :production_year %><br>
    <%= f.number_field :production_year, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :owner_id %><br>
    <%= f.collection_select :owner_id, @owners, :id, :owner_name, {prompt: "Select an owner"}, {class: "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

<script>
$('#project_date_production').datepicker({
    format: "yyyy-mm-dd",
    autoclose: true,
    todayHighlight: true
});
</script>

app/views/projects/_project_details.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="text-muted">Project Details</h3>
  </div>
  <div class="panel-body">
    <h4>Description</h4>
    <p><%= @project.description %></p>

    <h4>Production Notes</h4>
    <p><%= @project.production_notes %></p>

    <h4>Credits</h4>
    <p><%= @project.credits %></p>

    <h4>Production date</h4>
    <p><%= @project.date_production.try(:stamp, 'January 1, 2015') %></p>

    <h4>Production year</h4>
    <p><%= @project.production_year %></p>

    <h4>Owner</h4>
    <p><%= @project.owner.owner_name %></p>
  </div>
</div>

app/views/projects/digitize.html.erb
<div class="container">

<h1 class="green-text">Digitization for Tape <%= @physical.tape %></h1>
<p>
  <strong>Label Title and Info:</strong><br>
  <%= @physical.label_info %>
</p>
<p>
  <%= link_to fa_icon('eye', text: 'Show Tape Detail'), @physical, class: "btn btn-default" %>
  <%= link_to fa_icon('table', text: 'Back To All Tapes'), physicals_path, class: 'btn btn-default' %>
</p>

<%= form_for @project, url: {action: 'digitize'} do |project_fields| %>
  <div class="row">

      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Project Info</h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <%= project_fields.label :title %>
              <%= project_fields.text_field :title, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= project_fields.label :description %>
              <%= project_fields.text_area :description, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= project_fields.label :production_notes %>
              <%= project_fields.text_area :production_notes, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= project_fields.label :credits %>
              <%= project_fields.text_area :credits, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= project_fields.label :date_production, 'Production Date' %>
              <%= project_fields.date_field :date_production, class: 'form-control' %>
            </div>

            <div class="field form-group">
              <%= project_fields.label :owner_id %><br>
              <%= project_fields.collection_select :owner_id, @owners, :id, :owner_name, {prompt: "Select an owner", selected: @physical.owner_id}, {class: "form-control"} %>
            </div>

          </div>
        </div>
      </div>
    <%= fields_for :digitals do |digital_fields| %>
    <% end %>

  </div>
  <%= project_fields.submit 'Save Project', class: 'btn btn-success' %>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Editing Project</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @project %> |
    <%= link_to 'Back', projects_path %>
  </div>
</div>

app/views/projects/index.html.erb
<h1>Film Projects</h1>
<p>
  <%= link_to 'Enter a New Project', new_project_path, class: 'btn btn-default' %>
</p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Production notes</th>
      <th>Production date</th>
      <th>Production year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.production_notes %></td>
        <td><%= project.date_production %></td>
        <td><%= project.production_year %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  var offset = $('.navbar').height();
  $('table').stickyTableHeaders({fixedOffset: offset});
</script>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>New Project</h1>
    <%= render 'form' %>

    <%= link_to 'Back', projects_path %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
<h1 class="green-text"><%= @project.title %></h1>

<div class="row">
  <div class="col-sm-6">
    <%= render 'project_details' %>
  </div>
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="text-muted">Formats</h3>
      </div>
      <div class="panel-body">
      <h4>Tapes</h4>

      <% @project.physicals.each do |tape| %>
        <li>
          <%= link_to "Label ID #{tape.tape}", physical_path(tape) %>: <%= tape.label_info %>
        </li>
      <% end %>

      <h4>Drives</h4>
      <p><em>Coming soon!</em></p>
      <h4>Online</h4>
      <p><em>Coming soon!</em></p>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</div>