config/routes.rb
Rails.application.routes.draw do
  resources :tape_formats
  resources :formats
  resources :brands
  resources :conditions
  resources :physicals, path: 'tapes' do
    get 'digitize' => 'projects#digitize'
    post 'digitize' => 'projects#create_by_tape'
  end
  resources :digitals
  resources :projects
  resources :filmmakers
  resources :owners
  # resources :serials
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">

        <%= render 'layouts/navigation_links' %>

    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="nav navbar-nav">
  <li><%= link_to 'Projects', projects_path %></li>
  <li><%# link_to 'Filmmakers', filmmakers_path %></li>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Content <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%# link_to 'Drives', digitals_path %></li>
      <li><%= link_to 'Tapes', physicals_path %></li>
    </ul>
  </li>

  <% if user_signed_in? %>
    <% if current_user.admin? || current_user.vip? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Data <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% if current_user.admin? %>
            <li><%= link_to 'Users', users_path %></li>
          <% end %>
          <li><%= link_to 'Owners', owners_path %></li>
          <li class="divider"></li>
          <li><%= link_to 'Condition', conditions_path %></li>
          <li><%= link_to 'Tape Brands', brands_path %></li>
          <li><%= link_to 'Tape Formats', tape_formats_path %></li>
        </ul>
      </li>
    <% end %>
  <% end %>
  <li><%= link_to 'About', page_path('about') %></li>
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "NOVAC Digital Film Archive" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Novac Digital" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <%= image_tag("novac-logo-sm.png", alt: "NOVAC logo") %><br>

          </div>
          <div class="col-md-4">
            <a href="http://www.novacvideo.org/" target="_blank"><%= fa_icon "external-link" %> www.novacvideo.org</a><br>
            <a href="tel:5043081420"><%= fa_icon "phone" %> 504.308.1420</a><br>
            <%= mail_to "info@novacvideo.org" do %>
              <%= fa_icon "envelope-o" %> info@novacvideo.org
            <% end %>
          </div>
          <div class="col-md-4">
            <p>Follow us!</p>
            <p>
              <a href="https://www.facebook.com/novacvideo" target="_blank"><%= fa_icon "facebook", class: "fa-2x" %></a>
              <a href="https://twitter.com/NOVACneworleans" target="_blank"><%= fa_icon "twitter", class: "fa-2x" %></a>
              <a href="https://instagram.com/novacneworleans" target="_blank"><%= fa_icon "instagram", class: "fa-2x" %></a>
            </p>
            <p class="small">&copy; 2015 NOVAC  |  Website generated by <a href="http://www.clioandcalliope.com/" target="_blank">Clio+Calliope</a></p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>